# 基础镜像
FROM redis
# author
MAINTAINER InChh

# 挂载目录
VOLUME /home/exam/redis
# 创建目录
RUN mkdir -p /home/exam/redis
# 指定路径
WORKDIR /home/exam/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/exam/redis/redis.conf
