# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER InChh

# 挂载目录
VOLUME /home/exam
# 创建目录
RUN mkdir -p /home/exam
# 指定路径
WORKDIR /home/exam
# 复制jar文件到路径
COPY ./jar/exam-modules-file.jar /home/exam/exam-modules-file.jar
# 启动文件服务
ENTRYPOINT ["java","-jar","exam-modules-file.jar"]